{"data": "Traceback (most recent call last):\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/utils/zlog.py\", line 39, in log_context\n    yield self\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/proj/main/runscript.py\", line 140, in run_loop\n    runner = setup_runner(\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/proj/main/runscript.py\", line 92, in setup_runner\n    jiant_model_setup.delegate_load_from_path(\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/proj/main/modeling/model_setup.py\", line 90, in delegate_load_from_path\n    weights_dict = torch.load(weights_path)\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/torch/serialization.py\", line 791, in load\n    with _open_file_like(f, 'rb') as opened_file:\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/torch/serialization.py\", line 271, in _open_file_like\n    return _open_file(name_or_buffer, mode)\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/torch/serialization.py\", line 252, in __init__\n    super().__init__(open(name, mode))\nFileNotFoundError: [Errno 2] No such file or directory: '/work/projects/project02060/CyBERT/model/cybert_v100_epochs_20/model/model.p'\n", "TIMESTAMP": 1684230609.4993632}
