{"data": "Traceback (most recent call last):\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/jiant/utils/zlog.py\", line 39, in log_context\n    yield self\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/jiant/proj/main/runscript.py\", line 145, in run_loop\n    verbose=True,\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/jiant/proj/main/runscript.py\", line 93, in setup_runner\n    jiant_model=jiant_model, weights_path=args.model_path, load_mode=args.model_load_mode\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/jiant/proj/main/modeling/model_setup.py\", line 90, in delegate_load_from_path\n    weights_dict = torch.load(weights_path)\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/torch/serialization.py\", line 579, in load\n    with _open_file_like(f, 'rb') as opened_file:\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/torch/serialization.py\", line 230, in _open_file_like\n    return _open_file(name_or_buffer, mode)\n  File \"/home/mb14sola/.local/lib/python3.7/site-packages/torch/serialization.py\", line 211, in __init__\n    super(_open_file, self).__init__(open(name, mode))\nFileNotFoundError: [Errno 2] No such file or directory: '/work/projects/project01762/CyBERT/model/cybert_v100_r/model/model.p'\n", "TIMESTAMP": 1656933836.8992624}
